import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../Components/Navbar/Navbar";
import SideIcons from './_components/SideIcons';
import ScrollToTopButton from './_components/ScrollToTopButton';
import Footer from "../../Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TechSolutionor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="">
        <Navbar />
        <SideIcons />
        <ScrollToTopButton />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
